// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjgxeddgchpxuxoofkum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZ3hlZGRnY2hweHV4b29ma3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDI1NzUsImV4cCI6MjA3MjYxODU3NX0.gH_eR9R9oRuK1YMx8tVJydVuj4g_1uVZ7hj6Ubi3-xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});